### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by BrainBlasted**

### CODE REVIEW

**Comment by BrainBlasted** [comment]
The examples need to be updated, apparently.

**Comment by qdot** [comment]
Yeah, just looks like it wants a str instead of a char array. You got it or should I try to fix it?

**Comment by BrainBlasted** [comment]
You can fix it up. It's getting late where I am

**Comment by qdot** [comment]
Superceded by #3 to fix example issues and add set_title call.

**Pull request closed without merging**
